# Константы для экзамена
QUESTIONS_PER_STUDENT = 3
LUNCH_START_TIME = 30
LUNCH_DURATION_MIN = 12.0
LUNCH_DURATION_MAX = 18.0
BAD_MOOD_PROB = 1/8
GOOD_MOOD_PROB = 1/4
NEUTRAL_MOOD_PROB = 5/8
CONTINUE_ANSWER_PROB = 1/3
